name: UI-claudio-coder page
run-name: ${{github.actor}} is running UI-claudio-coder
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  UI-claudio-coder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Linters
        run: npm run lint

      - name: Format Code
        run: npm run format

      - name: Unit Test
        run: npm run test:coverage

      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
